# Codes are generated by ChatGPT

import re

text = "Hello 123, welcome 456!"

# Regex pattern to select the numbers
# and add the symbols []

# parameter 1 -> pattern to look for, in this case is any number
# parameter 2 -> refers to the first capture group (text the matches the pattern) and modifies it
# parameter 3 -> source

result = re.sub(r"(\d+)", r"[\1]", text)
print(result)

# Back references (/1, /2)
# parameter 1 -> pattern to look for, in this case is any word
# parameter 2 -> refers to the first and 2nd capture group
# parameter 3 -> source
name = "John Mateo"
result_name = re.sub(r"(\w+) (\w+)", r"\2, \1", name)
print(result_name)

# Non capturing groups
# parameter 1 -> pattern/words to look for, does not keep track of any matches
# parameter 2 -> text to replace any pattern detected
# parameter 3 -> source
fruits = "apple orange banana"
result_fruit = re.sub(r"(?:apple|banana)", "fruit", fruits)
print(result_fruit)

# Look ahead
price = "price: $100"
result_price = re.sub(r"\$(?=\d+)", "USD ", price )
print(result_price)

# Look behind
price2 = "USD100"
result_price2 = re.sub(r"(?<=USD)\d+", "XXX", price2 )
print(result_price2)